### ISSUE TITLE
Открытие ссылок в Цитате

### ISSUE THREAD

**Issue by YakushevVladimir** [YakushevVladimir/BibleQuote-for-Android#22]
По поводу ссылок. Возможно ли, чтобы ссылки такого типа http://b-bq.eu/Ezek/4_7/NRT система через контекстное меню предоставляла возможность открывать не только в интернет браузерах, но и в Цитате? Такая фишка реализована в Youth Bible. Тогда, например в конспекте проповеди, можно было бы вместо обширных местописаний вставлять ссылку на них. Кликаешь на такую ссылку, в открывшемся контекстном меню выбираешь Цитату и вуаля - читаешь нужное местописание. Кликаешь кнопку возврата, и ты снова в конспекте.

**Comment by ildar** [comment]
Уважаемые братья!
с сожалением я наблюдаю, что b-bq.eu прекратил своё существование. Если это
не будет исправлено в ближайшее время, то, пожалуй, надо BQ/Android
"переточить" на другую online-Библию. Спасибо.

**Comment by ildar** [comment]
Тимофей,
протокола, как такового, нет. Программа "перехватывает" обращения к URL
заданного образца и сама эти URL разбирает, после чего показывает
соответствующий отрывок на экране (как подмена WWW-страничке).
Единственное пожелание, если будете менять b-bq.eu на другой сайт: чтобы
тот сайт нормально открывался на маленьких экранах.
Во Христе, Иоанн.

**Comment by ildar** [comment]
а кто обслуживает bqapp.ru? Кажется, редиректы обламываются именно на нём.

2014-12-07 1:31 GMT+06:00 Ildar Mulyukov <ildar.mulyukov@gmail.com>:

> спасибо за попытку, но нет, в Android-е не работает. Только на компьютере.
>

**Comment by ildar** [comment]
как видно, веб-проекты, которые тут упоминались, уже очень мало интересуют
своих создателей. Поэтому перехожу на http://bibleonline.ru/
Кстати, Владимир, Вы не уточните статус Цитаты для Андроида? Уже всё?
Поскольку, Вы входите в команду, работающую над myBible, то, видимо, Цитате
будущего нет?
-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by YakushevVladimir** [comment]
Ильдар, здравствуйте!
Не спешите хоронить Цитату, пациент скорее жив чем мёртв. Надеюсь последние
коммиты говорят сами за себя. И я не являюсь членом команды MyBible. Просто
Денис дал мне доступ к своему исходному коду.
На данный момент Владимир Атапин совместно с Владимиром Яковлевым реализуют
API для доступа к модулям с сайта ph4.ru из Цитаты. Это позволит загружать
модули напрямую из приложения.
Если у вас есть какие-то предложения по ссылкам я готов вас выслушать. А
пока ваши замечания больше приносят негатива, чем позитива на работу.
14 июня 2015 г. 2:44 пользователь "ildar" <notifications@github.com>
написал:

**Comment by ildar** [comment]
Владимир, прошу прощения, если какие-то замечания были неподобающими. По
поводу Цитаты - искренне рад, что ошибся. А по поводу сайтов - этот вывод я
делаю с сожалением.
Предложение будет такое: сделать аналогичную поддержку для onlinebible.ru .
Там, кстати, тоже сделали авторедирект на мобильный сайт.

-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by YakushevVladimir** [comment]
Если бы onlinebible.ru <http://onlinebible.ru/> работала с модулями Цитаты, то не было бы никаких проблем. Ведь Цитата используется не только с русским синодальным, но и с кучей других модулей. У каждого модуля есть свой идентификатор, по которому определяется принадлежность текста. А указанный сайт, работает совсем иначе и будет достаточно сложно делать соответствие текстов Цитаты, к текстам данного сайта. 
______________________________________
С уважением,
Владимир Якушев
e-mail: ru.phoenix@gmail.com <mailto:ru.phoenix@gmail.com>
facebook: ru.phoenix <https://www.facebook.com/ru.phoenix>
twitter: @VYakushev <https://twitter.com/VYakushev>

**Comment by YakushevVladimir** [comment]
К сожалению, формат ссылок в онлайн-библии не совместим с форматом ссылок в Цитате. Да и Цитата - это в первую очередь программа рассчитанная на большое количество модулей с различными переводами. А здесь у онлайн-библии тоже своя дорога.
