### ISSUE TITLE
Опечатка в справке

### ISSUE THREAD

**Issue by YakushevVladimir** [YakushevVladimir/BibleQuote-for-Android#86]
"Но так как Android не закрывает приложения долгое время, то сворачивая и запуская приложение, вы на самомо деле открываете ранее запущенную программу..."

**Comment by ildar** [comment]
Так и есть. А в чём тут трудность?

**Comment by YakushevVladimir** [comment]
Никакой трудности. Просто памятка, чтобы исправить опечатку и не искать её по всему тексту.

**Comment by ildar** [comment]
ааа! не посмотрел на тему баги! извиняюсь за лишний шум.

2015-01-12 21:54 GMT+06:00 Vladimir Yakushev <notifications@github.com>:

> Никакой трудности. Просто памятка, чтобы исправить опечатку и не искать её
> по всему тексту.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YakushevVladimir/BibleQuote-for-Android/issues/86#issuecomment-69591128>
> .
>



-- 
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/
